services:
  user-ms-db:
    image: postgres:17.2
    container_name: user-ms-db
    environment:
      - POSTGRES_USER=postgresUserMs
      - POSTGRES_PASSWORD=postgresUserMs
      - POSTGRES_DB=user-ms-db
    ports:
      - 5432:5432
    volumes:
      - user-ms-db:/var/lib/postgresql/data

volumes:
  user-ms-db: