services:
  user-ms-db:
    image: postgres:17.2
    container_name: user-ms-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - user-ms-db:/var/lib/postgresql/data

volumes:
  user-ms-db: